{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.22/kotchan-0.2.22.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "ivlpy4a5yvgbzgzhn7ded2qioi"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotchan-jvm-0.2.22.jar",
          "url": "kotchan-jvm-0.2.22.jar",
          "size": 1260784,
          "sha1": "938a144dd2b1972160d8ac840f81b30bd2fbe115",
          "md5": "ea9dd62a33ec3003ef12524f45b9c6e9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan-jvm-0.2.22.jar",
          "url": "kotchan-jvm-0.2.22.jar",
          "size": 1260784,
          "sha1": "938a144dd2b1972160d8ac840f81b30bd2fbe115",
          "md5": "ea9dd62a33ec3003ef12524f45b9c6e9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.2.22/kotchan-metadata-0.2.22.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.2.22"
      }
    }
  ]
}
