{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.5/kotchan-0.2.5.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "vvxtxnew2rgwxbagu2f23uyh4y"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotchan-metadata-0.2.5.jar",
          "url": "kotchan-metadata-0.2.5.jar",
          "size": 226473,
          "sha1": "602bdf8ece00b0ee4c8f31e63fabb6aa1b3bab77",
          "md5": "76f93b85d7819f9486483232beca57f3"
        }
      ]
    }
  ]
}
