{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.17/kotchan-0.2.17.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "bpj7iogeqjcy5mrwcnhnumphju"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotchan-metadata-0.2.17.jar",
          "url": "kotchan-metadata-0.2.17.jar",
          "size": 228991,
          "sha1": "5844fafbf424bd1352009d963a7c064e19275bdb",
          "md5": "25441d0d83dfccd161d79cbc1e22d0c8"
        }
      ]
    }
  ]
}
