{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kotchan/0.3.4/kotchan-0.3.4.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "cskj2n7qebcyholhmvscs2tqvy"
    }
  },
  "variants": [
    {
      "name": "ios-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-native",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan.klib",
          "url": "kotchan-ios-0.3.4.klib",
          "size": 1215054,
          "sha1": "b97049dcf5665b8b97e4f9f5c0fd226dd15a08e3",
          "md5": "247a75ceed0dba267f9e0aea1d405458"
        },
        {
          "name": "kotchan-cinterop-vulkan.klib",
          "url": "kotchan-ios-0.3.4-cinterop-vulkan.klib",
          "size": 6272446,
          "sha1": "f7566dbdf94999cf8f2d413e81826da844bddcb9",
          "md5": "4243f845f848ef18480c402854e51c6c"
        },
        {
          "name": "kotchan-cinterop-kmvk.klib",
          "url": "kotchan-ios-0.3.4-cinterop-kmvk.klib",
          "size": 67049,
          "sha1": "9b63432d89446d8b0c22f2222d690f4da12bc952",
          "md5": "b71448d4b73c051f6f697168db7d56f0"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.3.4/kotchan-metadata-0.3.4.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.3.4"
      }
    }
  ]
}
