{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kotchan/0.4.0/kotchan-0.4.0.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "d35lzk32rffyvfp3ye7ns2vz7y"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotchan-jvm-0.4.0.jar",
          "url": "kotchan-jvm-0.4.0.jar",
          "size": 1313268,
          "sha1": "bcc7c0fee7528822a3865356c99fadf73e5520cb",
          "md5": "99d47f68382819bce834f3f4896d91ef"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan-jvm-0.4.0.jar",
          "url": "kotchan-jvm-0.4.0.jar",
          "size": 1313268,
          "sha1": "bcc7c0fee7528822a3865356c99fadf73e5520cb",
          "md5": "99d47f68382819bce834f3f4896d91ef"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.4.0/kotchan-metadata-0.4.0.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.4.0"
      }
    }
  ]
}
