{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.11/kotchan-0.2.11.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "i4q5z7csvjhqpb7gjwj5selp5u"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotchan-jvm-0.2.11.jar",
          "url": "kotchan-jvm-0.2.11.jar",
          "size": 1168840,
          "sha1": "e4f5b9b0a9a36121e8bd7b5e44e1511ce658e2ab",
          "md5": "7207980ef2021f861b9238fc4de83804"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.21"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan-jvm-0.2.11.jar",
          "url": "kotchan-jvm-0.2.11.jar",
          "size": 1168840,
          "sha1": "e4f5b9b0a9a36121e8bd7b5e44e1511ce658e2ab",
          "md5": "7207980ef2021f861b9238fc4de83804"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.2.11/kotchan-metadata-0.2.11.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.2.11"
      }
    }
  ]
}
