{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.18/kotchan-0.2.18.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "zdxv4iicq5elliloff3r2psxde"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotchan-metadata-0.2.18.jar",
          "url": "kotchan-metadata-0.2.18.jar",
          "size": 228991,
          "sha1": "c34ab6244dd5927e4a4af41987f3a20d5d1f8ce7",
          "md5": "5895910882d121605fcb142743690080"
        }
      ]
    }
  ]
}
