{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kotchan/0.4.0/kotchan-0.4.0.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "d35lzk32rffyvfp3ye7ns2vz7y"
    }
  },
  "variants": [
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotchan-release.aar",
          "url": "kotchan-android-0.4.0.aar",
          "size": 953987,
          "sha1": "2c8e0d55ee5227ac41c471796474fc283f08317d",
          "md5": "bdd6517dd42016ef52e5635b12f86656"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.0-RC"
          }
        },
        {
          "group": "com.android.support.constraint",
          "module": "constraint-layout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.50"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan-release.aar",
          "url": "kotchan-android-0.4.0.aar",
          "size": 953987,
          "sha1": "2c8e0d55ee5227ac41c471796474fc283f08317d",
          "md5": "bdd6517dd42016ef52e5635b12f86656"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.4.0/kotchan-metadata-0.4.0.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.4.0"
      }
    }
  ]
}
