{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.19/kotchan-0.2.19.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "asu5k6lffze3bgpuwgv3cac3ra"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotchan-metadata-0.2.19.jar",
          "url": "kotchan-metadata-0.2.19.jar",
          "size": 228991,
          "sha1": "b82303376723d3472d4f95ba70a4825ec58e2a8",
          "md5": "d061bbc7ba0962368cb268b08dc24854"
        }
      ]
    }
  ]
}
