{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.7/kotchan-0.2.7.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "godfwe6qw5dqnbee5j42pfcplq"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotchan-metadata-0.2.7.jar",
          "url": "kotchan-metadata-0.2.7.jar",
          "size": 226464,
          "sha1": "d444bb958aa0d30a04686d45adfaedd8b520b2f",
          "md5": "c67130fe40495059bb800a8d73ed21d6"
        }
      ]
    }
  ]
}
