{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.2/kotchan-0.2.2.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "zctshmijtvgx5fjup6b4545y2i"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotchan-jvm-0.2.2.jar",
          "url": "kotchan-jvm-0.2.2.jar",
          "size": 1156796,
          "sha1": "672e06a95b28e3aecbe3260a12c8bed0d60dd82c",
          "md5": "ea127c49416e6655c1200cfdaa4aab32"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.21"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan-jvm-0.2.2.jar",
          "url": "kotchan-jvm-0.2.2.jar",
          "size": 1156796,
          "sha1": "672e06a95b28e3aecbe3260a12c8bed0d60dd82c",
          "md5": "ea127c49416e6655c1200cfdaa4aab32"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.2.2/kotchan-metadata-0.2.2.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.2.2"
      }
    }
  ]
}
