{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kotchan/0.3.4/kotchan-0.3.4.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "cskj2n7qebcyholhmvscs2tqvy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotchan-jvm-0.3.4.jar",
          "url": "kotchan-jvm-0.3.4.jar",
          "size": 1266723,
          "sha1": "242f87938f8b1fed4b015c2c6762eea7684f531b",
          "md5": "32faf08bf8c25ae7075fd3a2e12cdc9e"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-vulkan",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan-jvm-0.3.4.jar",
          "url": "kotchan-jvm-0.3.4.jar",
          "size": 1266723,
          "sha1": "242f87938f8b1fed4b015c2c6762eea7684f531b",
          "md5": "32faf08bf8c25ae7075fd3a2e12cdc9e"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.3.4/kotchan-metadata-0.3.4.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.3.4"
      }
    }
  ]
}
