{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.3.3/kotchan-0.3.3.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.1.1",
      "buildId": "4ohv56jokbhr5e3durxp5p5dyq"
    }
  },
  "variants": [
    {
      "name": "ios-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-native",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan.klib",
          "url": "kotchan-ios-0.3.3.klib",
          "size": 1240892,
          "sha1": "6452090973f0cce29c17283fc13184037256eddb",
          "md5": "61054c78b4d34115997e5b23bf83bf60"
        },
        {
          "name": "kotchan-cinterop-vulkan.klib",
          "url": "kotchan-ios-0.3.3-cinterop-vulkan.klib",
          "size": 6272411,
          "sha1": "9250045366ec68ec3b85d426d7aa2e96ae84d858",
          "md5": "c678b999d8b55af899c0e1ae1a0a1015"
        },
        {
          "name": "kotchan-cinterop-kmvk.klib",
          "url": "kotchan-ios-0.3.3-cinterop-kmvk.klib",
          "size": 67126,
          "sha1": "9dabc23151d18c7415fdcfb889d4eb2b829b81d6",
          "md5": "5dbc2fab4d7786d5da54748e272ae366"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.3.3/kotchan-metadata-0.3.3.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.3.3"
      }
    }
  ]
}
