{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kotchan/0.3.3/kotchan-0.3.3.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "nz3zmrmvzjftvo24gsmfdfbk6e"
    }
  },
  "variants": [
    {
      "name": "ios-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.40"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-native",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan.klib",
          "url": "kotchan-ios-0.3.3.klib",
          "size": 1251374,
          "sha1": "65aea531c2ae8508707f9e1f1ff4eb7db90a9004",
          "md5": "1a273300bfc00f72e3b3ae5ac4c2a46a"
        },
        {
          "name": "kotchan-cinterop-vulkan.klib",
          "url": "kotchan-ios-0.3.3-cinterop-vulkan.klib",
          "size": 6268422,
          "sha1": "186573d34741a96b07322b067e35a427ae474e79",
          "md5": "2cd52eca20e5e8db80d0d39199404af4"
        },
        {
          "name": "kotchan-cinterop-kmvk.klib",
          "url": "kotchan-ios-0.3.3-cinterop-kmvk.klib",
          "size": 32567,
          "sha1": "2884b5ff51edc121e80a0b56fd18352399c2c908",
          "md5": "8c6aedc46a5f5abc468e1a2a1c107459"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.3.3/kotchan-metadata-0.3.3.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.3.3"
      }
    }
  ]
}
