{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.3.1/kotchan-0.3.1.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.1.1",
      "buildId": "wvgnvwxlcnbhzhf5r54kyv7g6q"
    }
  },
  "variants": [
    {
      "name": "ios-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-native",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan.klib",
          "url": "kotchan-ios-0.3.1.klib",
          "size": 1239107,
          "sha1": "e34befedd17fa3b0065141ef3e0839310dbe046f",
          "md5": "8f802ba2ee4c06bbb417f89ccab9152e"
        },
        {
          "name": "kotchan-cinterop-vulkan.klib",
          "url": "kotchan-ios-0.3.1-cinterop-vulkan.klib",
          "size": 6272408,
          "sha1": "c0cc3d62bd5ceab267713308692c9b07120ac0a4",
          "md5": "154891bd054aced475d6ad19b89e9d35"
        },
        {
          "name": "kotchan-cinterop-kmvk.klib",
          "url": "kotchan-ios-0.3.1-cinterop-kmvk.klib",
          "size": 67130,
          "sha1": "17bdd8ae4bdb4a672eb18a126c98d11d3e431db1",
          "md5": "61320ccdd66e9dbce8e70cbf49d6974"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.3.1/kotchan-metadata-0.3.1.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.3.1"
      }
    }
  ]
}
