{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.15/kotchan-0.2.15.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "blh3jz6stzabheuokfo4jitjlu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotchan-metadata-0.2.15.jar",
          "url": "kotchan-metadata-0.2.15.jar",
          "size": 228939,
          "sha1": "627fea4da0be0af33a675db119ced9c4d9b70cf1",
          "md5": "8984673498762e74e289a0254029e4b2"
        }
      ]
    }
  ]
}
