{
  "formatVersion": "0.4",
  "component": {
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "rdcjfn6k4bbh3fn6wtqxjahxji"
    }
  },
  "variants": [
    {
      "name": "ios-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotchan-ios/0.2.9/kotchan-ios-0.2.9.module",
        "group": "io.github.inoutch",
        "module": "kotchan-ios",
        "version": "0.2.9"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotchan-jvm/0.2.9/kotchan-jvm-0.2.9.module",
        "group": "io.github.inoutch",
        "module": "kotchan-jvm",
        "version": "0.2.9"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotchan-jvm/0.2.9/kotchan-jvm-0.2.9.module",
        "group": "io.github.inoutch",
        "module": "kotchan-jvm",
        "version": "0.2.9"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.2.9/kotchan-metadata-0.2.9.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.2.9"
      }
    }
  ]
}
