{
  "formatVersion": "1.0",
  "component": {
    "url": "../../kotchan/0.3.4/kotchan-0.3.4.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "cskj2n7qebcyholhmvscs2tqvy"
    }
  },
  "variants": [
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kotchan-release.aar",
          "url": "kotchan-android-0.3.4.aar",
          "size": 906756,
          "sha1": "2d8e9689d9a41a98ae42a336f551bc12c711abbc",
          "md5": "5b2cce5ad4f45296c6e3c705c428f507"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "com.android.support.constraint",
          "module": "constraint-layout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.9"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan-release.aar",
          "url": "kotchan-android-0.3.4.aar",
          "size": 906756,
          "sha1": "2d8e9689d9a41a98ae42a336f551bc12c711abbc",
          "md5": "5b2cce5ad4f45296c6e3c705c428f507"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.3.4/kotchan-metadata-0.3.4.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.3.4"
      }
    }
  ]
}
