{
  "formatVersion": "1.0",
  "component": {
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "nz3zmrmvzjftvo24gsmfdfbk6e"
    }
  },
  "variants": [
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotchan-android/0.3.3/kotchan-android-0.3.3.module",
        "group": "io.github.inoutch",
        "module": "kotchan-android",
        "version": "0.3.3"
      }
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kotchan-android/0.3.3/kotchan-android-0.3.3.module",
        "group": "io.github.inoutch",
        "module": "kotchan-android",
        "version": "0.3.3"
      }
    },
    {
      "name": "ios-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotchan-ios/0.3.3/kotchan-ios-0.3.3.module",
        "group": "io.github.inoutch",
        "module": "kotchan-ios",
        "version": "0.3.3"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotchan-jvm/0.3.3/kotchan-jvm-0.3.3.module",
        "group": "io.github.inoutch",
        "module": "kotchan-jvm",
        "version": "0.3.3"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotchan-jvm/0.3.3/kotchan-jvm-0.3.3.module",
        "group": "io.github.inoutch",
        "module": "kotchan-jvm",
        "version": "0.3.3"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.3.3/kotchan-metadata-0.3.3.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.3.3"
      }
    }
  ]
}
