{
  "formatVersion": "0.4",
  "component": {
    "url": "../../kotchan/0.2.4/kotchan-0.2.4.module",
    "group": "io.github.inoutch",
    "module": "kotchan",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.10.2",
      "buildId": "js3kkwo2mbdy7pymnf7dbmcima"
    }
  },
  "variants": [
    {
      "name": "ios-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotchan.klib",
          "url": "kotchan-ios-0.2.4.klib",
          "size": 2417363,
          "sha1": "867a502a715f7fc1bc10ed60bab412678e99d7dc",
          "md5": "4540a76787ba73c0113707b03ff39988"
        },
        {
          "name": "kotchan-cinterop-vulkan.klib",
          "url": "kotchan-ios-0.2.4-cinterop-vulkan.klib",
          "size": 5623276,
          "sha1": "85d764dfde3135443b4c5254d0f32848264d6f",
          "md5": "c387d16bd634b76d2fb5406b6c23a14"
        },
        {
          "name": "kotchan-cinterop-kmvk.klib",
          "url": "kotchan-ios-0.2.4-cinterop-kmvk.klib",
          "size": 36310,
          "sha1": "e291adc654af227edc4779cc7cbaeb79f899e1ad",
          "md5": "96f95b0bed39f0dc57538b6c0efac3a5"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "artifactType": "jar",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../kotchan-metadata/0.2.4/kotchan-metadata-0.2.4.module",
        "group": "io.github.inoutch",
        "module": "kotchan-metadata",
        "version": "0.2.4"
      }
    }
  ]
}
